### ISSUE TITLE
Support automatic log forwarding in next's app dir

### ISSUE THREAD

**Issue by kdembowski** [newrelic/newrelic-node-nextjs#126]
## Is your feature request related to a problem? Please describe.
Automatic (possibly manual as well) log forwarding does not seem to work in /app dir (considered stable since next 13.4). 

## Feature Description
Support for automatic log forwarding inside /app directory.

## Describe Alternatives
N/A

## Additional context
I was struggling to set up logging for a Next application using its new app router. It appears that automatic log forwarding simply does not work in React Server Components. Following newrelic's documentation I expected it to automatically forward logs when using a supported logger - I've tried both Winston and Pino. I've also tried manual logging with enricher plugins but as I understand they are not needed/deprecated(?)
To verify the issue is not in my setup I've created 2 basic Next.js repos - one using old /pages and one using [new app router](https://nextjs.org/docs/app/building-your-application/routing#the-app-directory). For the one with /pages logs were forwarded completely fine when logging from `getServerSideProps`. However for /app when logging from any server component it is not forwarded.

Here are the repos: 
/pages: https://github.com/kdembowski/newrelic-pages-repro/blob/main/pages/index.tsx
/app: https://github.com/kdembowski/newrelic-app-router-repro/blob/main/src/app/page.tsx

## Priority
Must Have

**Comment by VincentCtr** [comment]
Did you find any solution to send your logs ?

**Comment by andrewmclagan** [comment]
Not very encouraging: 

> added this to Triage Needed: Unprioritized Features

Can someone from NewRelic please give more information or a timeline? Thanks.

**Comment by kdembowski** [comment]
> Did you find any solution to send your logs ?

We switched to OpenTelemetry as it's integrated with Next.js

**Comment by andrewmclagan** [comment]
We also did this, although the OTEL data is nowhere near as rich as the full NewRelic integration. Not super useful TBH.

**Comment by bizob2828** [comment]
@kdembowski I took a look at this and it's because Next.js is using webpack to bundle dependencies.  We have an experimental plugin that can be used to fix issues that webpack causes but it appears to conflict with some of the other packages that Next.js relies on.  

I tried to use this

```sh
npm i @newrelic/webpack-plugin
```

and add this to next.config.js:

```
const NewrelicWebpackPlugin = require('@newrelic/webpack-plugin/lib/NewrelicWebpackPlugin')
const nodeExternals = require('@newrelic/webpack-plugin/lib/externals')
const nextConfig = {
  experimental: {
    appDir: true,
  },
  webpack: (config, options) => {
    config.externals.push(nodeExternals())
    config.plugins.push(new NewrelicWebpackPlugin())
    return config
  }
};
```

but when making requests I see this error

```

Error: Currently React only supports one RSC renderer at a time.
    at La (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:2426:66)
    at exports.renderToReadableStream (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:2447:54)
    at createRSCStream (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/server/app-render.js:386:38)
    at ServerComponentWrapper (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/server/app-render.js:398:27)
    at ae (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:99:272)
    at Z (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:105:91)
    at ae (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:103:386)
    at Z (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:105:91)
    at ae (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:103:386)
    at Z (/Users/revans/code/newrelic-app-router-repro/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:105:91)
```

**Comment by bizob2828** [comment]
I'm going to close this. Please let me know if this does not work for you.  I also introduced a PR to make this easier by automatically externalizing all libraries the Node.js agent instruments
