### ISSUE TITLE
Crash: newrelic.instrumentWebframework is not a function

### ISSUE THREAD

**Issue by 0xRapid** [newrelic/newrelic-node-nextjs#164]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Running my application using the newrelic/next which causes the application to crash

## Expected Behavior

Not crash I guess

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
```
node:internal/event_target:1016
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: newrelic.instrumentWebframework is not a function
    at Object.<anonymous> (/usr/src/app/node_modules/.pnpm/@newrelic+next@0.7.0_newrelic@11.1.0/node_modules/@newrelic/next/index.js:18:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1433:5)
    at loadPreloadModules (node:internal/process/pre_execution:598:5)
    at setupUserModules (node:internal/process/pre_execution:117:3)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:132:5)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17)
```

## Steps to reproduce

There's nothing special though, it's a big nextjs project, so putting it all here is irrelevant, and also it's a private repo.

ENV:
NODE_OPTIONS=-r @newrelic/next 

## Your Environment

**Alpine:** node:18.17.1-alpine
**Next:** v13.1.2

Running on an EKS cluster in AWS

**Comment by mrickard** [comment]
@0xRapid I'm sorry you're having trouble. Do you have the New Relic Node agent installed?

**Comment by 0xRapid** [comment]
> @0xRapid I'm sorry you're having trouble. Do you have the New Relic Node agent installed? 

Yes, of course. I am using new relic agent without any issues on all my other pods (more than 60) without any issue. In this case when it comes to a nextjs app, I followed the instructions from your website.

**Comment by mrickard** [comment]
@0xRapid Is this Next.js 13? We've been seeing similar issues and are investigating.

**Comment by 0xRapid** [comment]
@mrickard yep! Next.js 13.1.2

**Comment by Seyolas** [comment]
I'm having the same issue. This error occurs every second in my local. But it does not cause the crash the app. 
uncaughtException: TypeError [Error]: newrelic.instrumentWebframework is not a function
    at Object.<anonymous> (\node_modules\@newrelic\next\index.js:18:10)

My next.js version is 12.3.1 and not going to upgrade next.js 13 yet. 
Also when i build and start the project i see the data on new relic dashboard.

**Comment by 0xRapid** [comment]
hiya @mrickard , I'm updating nx and next to the latest versions, is 14.0.3 for nextjs supported?

**Comment by mrickard** [comment]
@0xRapid We have versioned tests for this repo, and 14.0.4 is covered and passing. I'll check 14.0.3.

**Comment by 0xRapid** [comment]
> @0xRapid We have versioned tests for this repo, and 14.0.4 is covered and passing. I'll check 14.0.3.
> 
> (Update: 14.0.3 passes our versioned tests, as well.)

Thanks, I'll probably have it tested the next couple of days then, and report/close :)

**Comment by pwestern** [comment]
For people who have experienced the same issue, hopefully this will be useful:

NextJS Version: 13.4.12, running inside Docker container

I was seeing periodic crashes in my NextJS application with the same error message. Turned out the cause was next/image, even though I wasn't using the component anywhere. Requests to `https://example.com/_next/image?url={imageUrl}&w={width}&q={quality}` would throw ```TypeError [Error]: newrelic.instrumentWebframework is not a function``` and cause the entire application to crash. The fix was to add the following to next.config.js
```
	images: {
		unoptimized: true,
	},
```
Obviously it would be great if this workaround wasn't needed but hopefully this is helpful for someone!
