### ISSUE TITLE
@newrelic/next 0.9.0 does not work with NextJS standalone Docker deployments.

### ISSUE THREAD

**Issue by raph90** [newrelic/newrelic-node-nextjs#197]
## Description

Hi all, I'm aware there is an earlier thread (#69) for a similar issue to this, but unfortunately every attempt I've made to follow that thread and use the suggestions there has failed. I'm at the point where I'm starting to think I won't be able to use NR for my app, which would be a shame. 

My deployment pipeline is Github actions, deploying to a VPS where I have a docker container that runs my app. 

My Dockerfile looks like this:
```
# Base stage for shared configuration
FROM node:20-alpine AS base
WORKDIR /app

ARG AUTH_SECRET
ENV AUTH_SECRET=${AUTH_SECRET}
ARG NEXT_PUBLIC_HOST
ENV NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

# Installing system dependencies (if necessary)
RUN apk add --no-cache libc6-compat

# Dependencies stage for caching node_modules separately
FROM base AS deps
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile;

RUN mkdir -p /newrelic
WORKDIR /newrelic
COPY <<EOF package.json
{
  "name": "newrelic-deps",
  "version": "1.0.0",
  "dependencies": {
    "@newrelic/next": "^0.9.0"
  }
}
EOF
RUN corepack enable pnpm && pnpm i

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY .env.local ./.env.local
RUN npx prisma generate
RUN corepack enable pnpm && pnpm run build;
RUN npm run typecheck

# Runner stage for the production environment
FROM base AS production
WORKDIR /app
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next
RUN touch ./newrelic_agent.log
RUN chown nextjs:nodejs ./newrelic_agent.log

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/newrelic.js ./

COPY --from=deps /newrelic/node_modules ./node_modules

USER nextjs
EXPOSE 3000
ENV PORT 3000
ENV AUTH_TRUST_HOST true
CMD HOSTNAME="0.0.0.0" node -r @newrelic/next server.js
```

You can see that I've tried installing @newrelic/next in a subdirectory and copying over the node_modules folder to try and make @newrelic/next available when I run the server. If I don't do this, I get 'unable to find module etc.'  However, now that I'm doing that, I'm getting the following error:

```
SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4306:19)
    at successSteps (node:internal/deps/undici/undici:4288:27)
    at fullyReadBody (node:internal/deps/undici/undici:2724:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:4297:7)
    at async n (/app/.next/server/chunks/764.js:4:1831)
    at async C (/app/.next/server/chunks/764.js:1:4965) {
  digest: '3143420196'
}
```

This looks to me like it's something to do with how I'm rendering my app on the frontend, but my layout.tsx file looks like this:

```tsx
import newrelic from 'newrelic';
import { ColorSchemeScript } from '@mantine/core';
import '@mantine/core/styles.layer.css';
import '@mantine/dates/styles.layer.css';
import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';
import '../theme/globals.css';
import Script from 'next/script';
import SessionAndThemeProvider from '@/lib/SessionAndThemeProvider';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-ignore
  if (!newrelic.agent.collector.isConnected()) {
    await new Promise((resolve) => {
      // @ts-ignore
      newrelic.agent.on('connected', resolve);
    });
  }

  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true,
    //@ts-ignore
    allowTransactionlessInjection: true,
  });

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className="antialised">
        <SessionAndThemeProvider>{children}</SessionAndThemeProvider>
      </body>
      <Script
        id="nr-browser-agent"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{ __html: browserTimingHeader }}
      />
    </html>
  );
}

```

If I try to use the instrumentation hook as suggested in the other issue, that also doesn't work. 

My next config looks like this:

```js
const bundleAnalyzer = require('@next/bundle-analyzer');
const nrExternals = require('@newrelic/next/load-externals');

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  reactStrictMode: false,
  eslint: {
    ignoreDuringBuilds: true,
  },
  webpack: (config) => {
    nrExternals(config);
    return config;
  },
  experimental: {
    optimizePackageImports: ['@mantine/core', '@mantine/hooks', '@mantine/form', '@mantine/dates'],
    serverActions: {
      allowedOrigins: ['localhost:3000'],
    },
    serverComponentsExternalPackages: ['newrelic'],
  },
  output: 'standalone',
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'my-app-name.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
});

```

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

I would expect to be able to use New Relic in a docker container-hosted Next app, running on a basic server.

## Steps to Reproduce

- spin up new VPS. 
- create new next app
- use files above

## Your Environment

digital ocean droplet running ubuntu.

**Comment by raph90** [comment]
I don't think these errors were caused by New Relic - I think instead it was because my VPS was out of memory, so closing this.
