### ISSUE TITLE
Cannot read properties of undefined (reading 'RecorderSpec')

### ISSUE THREAD

**Issue by dimitriBouteille** [newrelic/newrelic-node-nextjs#200]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

```
TypeError: Cannot read properties of undefined (reading 'RecorderSpec')
    at DevServer.renderHTMLRecorder (/node_modules/@newrelic/next/lib/next-server.js:84:31)
    at DevServer.wrapper (/node_modules/newrelic/lib/shim/shim.js:887:31)
    at doRender (/node_modules/next/dist/server/base-server.js:687:49)
    at cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/node_modules/next/dist/server/base-server.js:796:34)
    at /node_modules/next/dist/server/response-cache/index.js:80:42
    at ResponseCache.get (/node_modules/next/dist/server/response-cache/index.js:128:11)
    at DevServer.renderToResponseWithComponents (/node_modules/next/dist/server/base-server.js:718:53)
    at DevServer.wrappedRenderToResponseWithComponents [as renderToResponseWithComponents] (/node_modules/@newrelic/next/lib/next-server.js:58:27)
    at DevServer.renderErrorToResponse (/node_modules/next/dist/server/base-server.js:1113:29)
    at async pipe.req.req (/node_modules/next/dist/server/base-server.js:1033:30)
    at async DevServer.pipe (/node_modules/next/dist/server/base-server.js:387:25)
    at async DevServer.run (/node_modules/next/dist/server/dev/next-dev-server.js:715:24)
    at async DevServer.handleRequest (/node_modules/next/dist/server/base-server.js:303:20)
```

## Steps to Reproduce

- Install next.js 12.x
- Add @newrelic/next and newrelic dependencies
- Run app
- :boom: 

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

- [@newrelic/next](https://www.npmjs.com/package/@newrelic/next) version: `0.9.0` (same error with `0.8.0` but good with `0.7.0`)
- @types/newrelic version: `9.14.4`
- [newrelic](https://www.npmjs.com/package/newrelic) version: `11.10.0`
- Node version: `16.15.1`
- Operating System and version: `Ubuntu 22.04.1 LTS`

**Comment by bizob2828** [comment]
You need to be using newrelic@11.11.0+

**Comment by jsumners-nr** [comment]
Also, please refer to our example apps https://github.com/newrelic/newrelic-node-nextjs#example-projects
